# Etapa 1 — Build da aplicação
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Passando variável de build
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Build da aplicação
RUN npm run build

# Etapa 2 — Servir com Nginx
FROM nginx:alpine

# Copiando os arquivos estáticos
COPY --from=build /app/dist /usr/share/nginx/html

# Remover default.conf se quiser configurar
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
